#!/usr/bin/env python3
"""Phase 12 (scoped #1b): self-righting reliability at perturbed I_bot,
side_rest and full_inversion buckets.

Scope, per explicit direction: side_rest (85-95deg) is primary --
the ~50% baseline recovery rate is the most sensitive to change, so it's
the strongest test of whether the lumped-mass approximation matters for
the active-control regime. full_inversion (170-180deg) is included too
since it only required a parameter change in this same harness (no new
spawn logic) -- the decision rule for skipping it (significant new
harness work) did not apply. moderate is explicitly OUT of scope per
Phase 11's finding: it recovers via passive settling, not the active RW
maneuver, so it isn't informative about I_bot sensitivity in the same way.

Baseline (I_bot unperturbed) is NOT rerun here -- reusing
phase7_full_revalidation/self_righting_3bucket_results.json's existing
side_rest (10/20) and full_inversion (3/20) numbers directly. Valid reuse
because landing_controller.py's RIGHTING state machine was untouched by
both Phase 9 (hopper_locomotion.py launch-timing fix only) and Phase 11
(harness-side timer instrumentation only, no controller change) -- the
baseline behavior is bit-for-bit the same code path measured in Phase 7.

Perturbed configs: spacehopper_ibot_p20 (all 6 base_link inertia-tensor
components x1.20) and spacehopper_ibot_m20 (x0.80), generated by
generate_ibot_variants.py. Mass and COM unperturbed (out of this scoped
run). Same core methodology as
phase7_full_revalidation/self_righting_batch_3bucket.py (n=20/bucket per
config, SPAWN_Z=5.2, LANDED_WAIT_TIMEOUT=350s, RIGHTING_WAIT_TIMEOUT=120s,
SUCCESS_UZ=0.9), plus Phase 11's recovery-timer fix (times off
/righting_active's first True transition, not the landed-poll loop).

Run: python3 mass_sensitivity_self_righting.py
"""
import json, math, os, subprocess, time, random

PHASE12_DIR = os.path.dirname(__file__)
os.environ['GZ_SIM_RESOURCE_PATH'] = (
    '/home/melvin/ryugu_v2_ws/src/ryugu_sim/models:' + f'{PHASE12_DIR}/variant_models')

import rclpy
from rclpy.node import Node
from nav_msgs.msg import Odometry
from std_msgs.msg import Bool

LOG_DIR = PHASE12_DIR
OUT = f"{LOG_DIR}/mass_sensitivity_self_righting_results.json"
BRIDGE_YAML = "/tmp/ryugu_bridge_scout_1_p12.yaml"
WORLD = '/home/melvin/ryugu_v2_ws/src/ryugu_sim/worlds/ryugu.sdf'
N_PER_CONFIG = 20
SUCCESS_UZ = 0.9
SPAWN_Z = 5.2
LANDED_WAIT_TIMEOUT = 350.0
RIGHTING_WAIT_TIMEOUT = 120.0

BUCKETS = [
    ("side_rest", 85.0, 95.0),
    ("full_inversion", 170.0, 180.0),
]
CONFIGS = [
    ("ibot_p20", "model://spacehopper_ibot_p20"),
    ("ibot_m20", "model://spacehopper_ibot_m20"),
]


def kill_scout1_nodes():
    subprocess.run(['pkill', '-9', '-f',
                     'bridge_scout_1|loco_scout_1|attitude_scout_1|landing_scout_1'],
                    capture_output=True)
    time.sleep(1.5)


def make_bridge_yaml():
    imu_gz_topic = '/world/ryugu_world/model/scout_1/link/base_link/sensor/imu_sensor/imu'
    entries = [
        ('/scout_1/imu', imu_gz_topic, 'sensor_msgs/msg/Imu', 'gz.msgs.IMU', 'GZ_TO_ROS'),
        ('/scout_1/odometry', '/model/scout_1/odometry', 'nav_msgs/msg/Odometry', 'gz.msgs.Odometry', 'GZ_TO_ROS'),
    ]
    for axis in ['x', 'y', 'z']:
        entries.append((f'/scout_1/rw_{axis}_joint_cmd_vel',
                         f'/model/scout_1/joint/rw_{axis}_joint/cmd_vel',
                         'std_msgs/msg/Float64', 'gz.msgs.Double', 'ROS_TO_GZ'))
    for j in range(3):
        for jt in ['hip', 'knee']:
            entries.append((f'/scout_1/joint_{jt}_joint_{j}_cmd_pos',
                             f'/model/scout_1/joint/{jt}_joint_{j}/0/cmd_pos',
                             'std_msgs/msg/Float64', 'gz.msgs.Double', 'ROS_TO_GZ'))
    entries.append(('/scout_1/cmd_drill', '/model/scout_1/joint/drill_joint/0/cmd_pos',
                     'std_msgs/msg/Float64', 'gz.msgs.Double', 'ROS_TO_GZ'))
    with open(BRIDGE_YAML, 'w') as f:
        for ros_t, gz_t, ros_ty, gz_ty, dr in entries:
            f.write(f'- ros_topic_name: "{ros_t}"\n  gz_topic_name: "{gz_t}"\n'
                     f'  ros_type_name: "{ros_ty}"\n  gz_type_name: "{gz_ty}"\n  direction: {dr}\n')


def launch_scout1_nodes(label, idx):
    specs = [
        ('bridge_scout_1', ['ros2', 'run', 'ros_gz_bridge', 'parameter_bridge',
         '--ros-args', '-r', '__node:=bridge_scout_1', '--params-file', '/dev/null',
         '-p', f'config_file:={BRIDGE_YAML}']),
        ('landing_scout_1', ['ros2', 'run', 'ryugu_sim', 'landing_controller', 'scout_1',
         '--ros-args', '-r', '__node:=landing_scout_1']),
    ]
    for name, cmd in specs:
        logf = open(f"{LOG_DIR}/{name}_{label}_trial{idx}.log", 'w')
        subprocess.Popen(cmd, stdout=logf, stderr=subprocess.STDOUT)
    time.sleep(4)


def tilt_quaternion(tilt_deg, azimuth_deg):
    half = math.radians(tilt_deg) / 2.0
    az = math.radians(azimuth_deg)
    s = math.sin(half)
    return (s * math.cos(az), s * math.sin(az), 0.0, math.cos(half))


def gz_respawn(model_uri, x, y, z, quat):
    subprocess.run(['gz', 'service', '-s', '/world/ryugu_world/remove',
                     '--reqtype', 'gz.msgs.Entity', '--reptype', 'gz.msgs.Boolean',
                     '--timeout', '3000', '--req', "name: 'scout_1', type: MODEL"],
                    capture_output=True)
    time.sleep(1.5)
    qx, qy, qz, qw = quat
    req = (f"sdf_filename: '{model_uri}', name: 'scout_1', "
           f"pose {{ position {{ x: {x} y: {y} z: {z} }} "
           f"orientation {{ x: {qx} y: {qy} z: {qz} w: {qw} }} }}")
    subprocess.run(['gz', 'service', '-s', '/world/ryugu_world/create',
                     '--reqtype', 'gz.msgs.EntityFactory', '--reptype', 'gz.msgs.Boolean',
                     '--timeout', '3000', '--req', req], capture_output=True)


def start_world(log):
    log("  (re)starting gz sim daemon...")
    gz_log = open(f"{LOG_DIR}/gz_p12_batch.log", 'a')
    subprocess.Popen(['gz', 'sim', '-r', '--headless-rendering', WORLD],
                      stdout=gz_log, stderr=subprocess.STDOUT)
    time.sleep(8)


def kill_all():
    subprocess.run(['pkill', '-9', '-f',
                     'bridge_scout_1|loco_scout_1|attitude_scout_1|landing_scout_1'],
                    capture_output=True)
    subprocess.run(['pkill', '-9', '-f', 'gz sim'], capture_output=True)
    time.sleep(2)


class TrialMonitor(Node):
    def __init__(self):
        super().__init__('p12_mass_sens_monitor')
        self.uz = None
        self.landed = None
        self.righting_started_at = None
        self.create_subscription(Odometry, '/scout_1/odometry', self.odom_cb, 20)
        self.create_subscription(Bool, '/scout_1/landed', self.landed_cb, 10)
        self.create_subscription(Bool, '/scout_1/righting_active', self.righting_cb, 10)

    def odom_cb(self, msg):
        q = msg.pose.pose.orientation
        self.uz = 1 - 2 * (q.x * q.x + q.y * q.y)

    def landed_cb(self, msg):
        self.landed = msg.data

    def righting_cb(self, msg):
        if msg.data and self.righting_started_at is None:
            self.righting_started_at = time.time()

    def spin_for(self, seconds):
        rclpy.spin_once(self, timeout_sec=min(0.2, seconds))


def run_one_trial(bucket_label, lo, hi, config_tag, model_uri, trial_idx, log):
    tilt_deg = random.uniform(lo, hi)
    az = random.uniform(0, 360)
    trial_label = f"{bucket_label}_{config_tag}"

    kill_scout1_nodes()
    quat = tilt_quaternion(tilt_deg, az)
    gz_respawn(model_uri, 0.0, 0.5, SPAWN_Z, quat)
    launch_scout1_nodes(trial_label, trial_idx)

    rclpy.init()
    node = TrialMonitor()
    t0 = time.time()
    while node.uz is None and time.time() - t0 < 10.0:
        node.spin_for(0.2)
    start_uz = node.uz
    log(f"  [{trial_label} trial{trial_idx}/{N_PER_CONFIG}] commanded_tilt={tilt_deg:.1f} "
        f"az={az:.0f} start_uz={start_uz}")

    land_t0 = time.time()
    while time.time() - land_t0 < LANDED_WAIT_TIMEOUT and node.landed is not True:
        node.spin_for(0.3)
    log(f"    landed={node.landed} after {time.time()-land_t0:.1f}s uz={node.uz}")

    outcome = "no_landing"
    final_uz = node.uz
    recover_time_s = None
    landed_flag = node.landed
    if node.landed is True:
        wait_t0 = time.time()
        recovered = False
        while time.time() - wait_t0 < RIGHTING_WAIT_TIMEOUT:
            node.spin_for(0.2)
            if node.uz is not None and node.uz > SUCCESS_UZ:
                recovered = True
                if node.righting_started_at is not None:
                    recover_time_s = time.time() - node.righting_started_at
                break
        final_uz = node.uz
        outcome = "recovered" if recovered else "failed"
        log(f"    outcome={outcome} final_uz={final_uz} "
            f"righting_started_at={node.righting_started_at} recover_time_s={recover_time_s}")

    node.destroy_node()
    rclpy.shutdown()

    return {
        "bucket": bucket_label, "config": config_tag, "trial": trial_idx,
        "commanded_tilt_deg": tilt_deg, "azimuth_deg": az, "start_uz": start_uz,
        "landed": landed_flag, "final_uz": final_uz, "outcome": outcome,
        "righting_started_at": node.righting_started_at, "recover_time_s": recover_time_s,
    }


def wilson_ci(k, n, z=1.959963985):
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    denom = 1 + z * z / n
    center = (p + z * z / (2 * n)) / denom
    half = (z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))) / denom
    return (max(0.0, center - half), min(1.0, center + half))


def main():
    def log(msg):
        print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)

    kill_all()
    start_world(log)
    make_bridge_yaml()

    results = []
    for bucket_label, lo, hi in BUCKETS:
        for config_tag, model_uri in CONFIGS:
            log(f"=== bucket={bucket_label} ({lo}-{hi}deg) config={config_tag} "
                f"({model_uri}), n={N_PER_CONFIG} ===")
            for i in range(N_PER_CONFIG):
                r = run_one_trial(bucket_label, lo, hi, config_tag, model_uri, i + 1, log)
                results.append(r)
                with open(OUT, 'w') as f:
                    json.dump(results, f, indent=2)
            # Fresh daemon between (bucket, config) blocks -- cheap insurance
            # against any accumulated daemon-session drift (cf. Phase 10's
            # mu=0.75 gz-transport fault).
            kill_all()
            start_world(log)

    log("=== mass-sensitivity batch complete ===")
    BASELINE = {"side_rest": (10, 20), "full_inversion": (3, 20)}
    for bucket_label, _, _ in BUCKETS:
        base_k, base_n = BASELINE[bucket_label]
        base_p = base_k / base_n
        log(f"--- {bucket_label} (baseline, Phase 7, reused not rerun: "
            f"{base_k}/{base_n} = {base_p:.1%}) ---")
        for config_tag, _ in CONFIGS:
            bucket_results = [r for r in results
                               if r["bucket"] == bucket_label and r["config"] == config_tag]
            n = len(bucket_results)
            n_rec = sum(1 for r in bucket_results if r["outcome"] == "recovered")
            lo_ci, hi_ci = wilson_ci(n_rec, n)
            times = [r["recover_time_s"] for r in bucket_results if r["recover_time_s"] is not None]
            log(f"  {config_tag}: {n_rec}/{n} recovered ({n_rec/n:.1%}), "
                f"95% CI [{lo_ci:.1%}, {hi_ci:.1%}]")
            if times:
                mean_t = sum(times) / len(times)
                std_t = math.sqrt(sum((t - mean_t) ** 2 for t in times) / len(times)) if len(times) > 1 else 0.0
                log(f"    recover_time_s: n={len(times)} mean={mean_t:.2f} std={std_t:.2f} "
                    f"min={min(times):.2f} max={max(times):.2f}")
            else:
                log(f"    recover_time_s: no successful /righting_active-timed recoveries")


if __name__ == '__main__':
    main()
