#!/usr/bin/env python3
"""Convert Research_Paper.md into markdown ready for the official IEEE
conference-template-A4.docx via pandoc --reference-doc.

The template's heading styles carry Word auto-numbering (Heading1 =
Roman numerals via numId 4 ilvl0, Heading2 = letters via ilvl1, Heading3
via ilvl2), so the manual "1. "/"3.1 "/"3.1.1 " prefixes in the source
must be stripped -- otherwise every section would show a doubled number
("I. 1. Introduction"). Pandoc maps markdown heading level to docx style
by NAME (h1->"Heading 1", h2->"Heading 2", ...), so section levels here
are shifted up by one relative to the source (## -> #, ### -> ##,
#### -> ###) to line up with the template's Heading1/2/3, and the paper
title itself is emitted as a plain paragraph (not a heading) since it
needs the template's "papertitle" style, not "Heading 1" -- retargeted
in post-processing since it's reliably the first paragraph in the body.

Similarly, figure/table/reference numbering is auto-generated by the
template's list-numbered styles (figurecaption, tablehead, references),
so "Figure N: "/"Table N. "/"[N] " prefixes are stripped here; the
apply_ieee_template_styles.py post-processing step assigns the actual
paragraph styles by content pattern.
"""
import re

SRC = '../Research_Paper.md'
OUT = 'paper_ieee.md'

DIAGRAM_PNG = {3: 'd1-1.png', 12: 'd2-1.png', 15: 'd3-1.png', 16: 'd4-1.png'}

KEYWORDS = ("asteroid exploration, legged locomotion, hopping robots, "
            "reaction wheels, swarm robotics, milli-gravity, planetary "
            "surface mobility")

md = open(SRC, encoding='utf-8').read()
lines = md.split('\n')
out = []
i = 0
n = len(lines)
fig_n = 0

while i < n:
    line = lines[i]
    stripped = line.strip()

    # --- title: first line, "# ..." -> plain paragraph, no heading ---
    if i == 0 and stripped.startswith('# '):
        out.append(stripped[2:])
        out.append('')
        i += 1
        continue

    # --- authors div -> Author-styled name line + Affiliation lines ---
    if stripped.startswith('<div class="authors">'):
        depth = 0
        block = []
        while i < n:
            depth += lines[i].count('<div') - lines[i].count('</div>')
            block.append(lines[i])
            i += 1
            if depth <= 0:
                break
        text = '\n'.join(block)
        name_m = re.search(r'<div class="author-line">(.*?)</div>', text)
        affil_m = re.search(r'<div class="affil">(.*?)</div>', text)
        corr_m = re.search(r'<div class="corr">(.*?)</div>', text)
        if name_m:
            out.append('%%AUTHOR%%' + re.sub(r'&nbsp;', ' ', name_m.group(1)).replace('<sup>*</sup>', '*'))
            out.append('')
        if affil_m:
            out.append('%%AFFIL%%' + affil_m.group(1))
            out.append('')
        if corr_m:
            out.append('%%AFFIL%%' + re.sub(r'<sup>\*</sup>', '*', corr_m.group(1)))
            out.append('')
        continue

    # --- abstract div -> plain "Abstract-..." paragraph ---
    if stripped.startswith('<div class="abstract">'):
        depth = 0
        block = []
        while i < n:
            depth += lines[i].count('<div') - lines[i].count('</div>')
            block.append(lines[i])
            i += 1
            if depth <= 0:
                break
        text = '\n'.join(block)
        em_m = re.search(r'<em>(.*?)</em>', text, re.S)
        if em_m:
            out.append('%%ABSTRACT%%Abstract—' + em_m.group(1).strip())
            out.append('')
            out.append('%%KEYWORDS%%Keywords—' + KEYWORDS)
            out.append('')
        continue

    # --- nomenclature divs -> plain bold-lead-in body paragraphs ---
    if stripped.startswith('<div class="nomenclature">'):
        depth = 0
        block = []
        while i < n:
            depth += lines[i].count('<div') - lines[i].count('</div>')
            block.append(lines[i])
            i += 1
            if depth <= 0:
                break
        text = '\n'.join(block)
        inner = re.sub(r'</?div[^>]*>', '', text).strip()
        inner = re.sub(r'<strong>(.*?)</strong>', r'**\1**', inner)
        out.append(inner)
        out.append('')
        continue

    # --- section headings: strip manual numbers, shift level ---
    m4 = re.match(r'^#### \d+\.\d+\.\d+ (.+)$', stripped)
    if m4:
        out.append('### ' + m4.group(1))
        i += 1
        continue
    m3 = re.match(r'^### \d+\.\d+ (.+)$', stripped)
    if m3:
        out.append('## ' + m3.group(1))
        i += 1
        continue
    m2 = re.match(r'^## \d+\. (.+)$', stripped)
    if m2:
        out.append('# ' + m2.group(1))
        i += 1
        continue
    # unnumbered component heads (Data Availability, Acknowledgment,
    # References) -> Heading5, matched by NOT having a leading digit
    m2u = re.match(r'^## ([A-Z][a-z].+)$', stripped)
    if m2u and not re.match(r'^\d', m2u.group(1)):
        out.append('##### ' + m2u.group(1))
        i += 1
        continue

    # --- figure captions: "*Figure N: text*" -> plain "%%FIGCAP%%text" ---
    mfig = re.match(r'^\*Figure \d+: (.+)\*$', stripped)
    if mfig:
        out.append('%%FIGCAP%%' + mfig.group(1))
        i += 1
        continue

    # --- table captions: "**Table N. text**" -> "%%TABHEAD%%text" ---
    mtab = re.match(r'^\*\*Table [IVX]+\. (.+)\*\*$', stripped)
    if mtab:
        out.append('%%TABHEAD%%' + mtab.group(1))
        i += 1
        continue

    # --- references: "[N] text" -> "%%REF%%text", each its own paragraph.
    # The source has no blank line between consecutive [N] entries (one
    # per line is the natural reference-list format), but markdown needs
    # a blank line to treat consecutive lines as separate paragraphs --
    # without it pandoc merges the whole list into one run-on paragraph
    # with only the first entry's auto-number rendering. ---
    mref = re.match(r'^\[\d+\] (.+)$', stripped)
    if mref:
        out.append('%%REF%%' + mref.group(1))
        out.append('')
        i += 1
        continue

    # --- mermaid diagrams -> pre-rendered PNGs, matched by NEW (shifted)
    # figure number two lines down (which is now unprefixed caption text,
    # so match by proximity to the DIAGRAM_PNG source list order instead) ---
    if stripped.startswith('```mermaid'):
        i += 1
        while i < n and not lines[i].strip().startswith('```'):
            i += 1
        i += 1
        j = i
        while j < n and lines[j].strip() == '':
            j += 1
        # the next non-blank line is now "![...](...)" for the diagram already? no -
        # in source, diagram figures are mermaid-only (no separate image line), followed
        # directly by the (still-numbered, not yet stripped at this point in the pass)
        # "*Figure N:" caption. Re-check against the ORIGINAL source numbering.
        cm = re.match(r'\*Figure (\d+):', lines[j].strip()) if j < n else None
        if cm:
            fign = int(cm.group(1))
            png = DIAGRAM_PNG.get(fign)
            if png:
                out.append(f'![diagram]({png})')
                out.append('')
        continue

    out.append(line)
    i += 1

open(OUT, 'w', encoding='utf-8').write('\n'.join(out))
print('wrote', OUT, len(out), 'lines')
